#!/usr/bin/env bash
#task 0

printInfo (){
	i=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t ' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $i" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 1 ];
then
	sub=("www" "lb-01" "web-01" "web-02")
	for i in "${sub[@]}"
	do
		printInfo "$1" "$i";
	done
else
	printInfo "$1" "$2"
fi
