#!/usr/bin/env bash
#task 0 kkkkkkkkkkkkkkkkkkkkkkk
printInfo (){
	dig "$2"."$1" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
}

if [ "$#" -eq 1 ];
then
	sub=("www" "lb-01" "web-01" "web-02")
	for i in "${sub[@]}"
	do
		printInfo "$1" "$i";
	done
else
	printInfo "$1" "$2"
fi

