#!/usr/bin/env bash
#task 1

apt-get update
apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.html
printf %s "server {
	listen 80;
	listen [::]:80;
	root   /var/www/html;
	index  index.html;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
    
}" > /etc/nginx/sites-available/default

service nginx restart
