#!/usr/bin/env bash
# badd goodd

i=1
while ((i <= 10))
do
    if ((i != 4 && i != 8))
    then
        echo "Best School"
    elif ((i == 4))
    then
        echo "bad luck"
    else
        echo "good luck"
    fi
	((i++))
done
