#!/usr/bin/env bash
# task 9
f="school"
if [ -e "$f" ]
then
	echo "$f file exists"
	if [ -s "$f" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$f" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
